### ISSUE TITLE
Pseudo Code JS 

### ISSUE THREAD

**Issue by rhazama** [katcontrerasdev/thePlantsProject#11]
figure out functions in js

**Comment by katcontrerasdev** [comment]
1. User’s get a welcome, with formatted date and time.

2. User gets some text input form asking them if they want to learn? or be a mentor. 

3. Learn* 
 - They will get a series of 5 questions
- They will get a result 
- They will get a personality type/or description of what it means 
- Give them an idea/or on how to be a plant parent with youtube video 
- Option to be assigned a Plant mentor. 

4. Mentor*
- Will answer survey about what skills they can offer and schedule
- Get matched with a new plant parent 
- follow-up?

5. Database Submission* (Airtable) 
- Plant Common Name 
- Plant Scientific Name
- Plant Image 
- Plant personality - type 
- Care Instructions
