### ISSUE TITLE
finalize 7 houseplants

### ISSUE THREAD

**Issue by rhazama** [katcontrerasdev/thePlantsProject#13]

**Comment by katcontrerasdev** [comment]
Swiss Cheese Plant (Monstera Deliciosa)
Variegated Rubber Plant
Bird of Paradise (Strelitzia)
Devil's Ivy Epipremnum aureum 
Fern Leaf Cactus
Wax Plant 
Begonias
Peacock Plant
Satin Pothos

**Comment by katcontrerasdev** [comment]
I took images of the plants with little description from a book called indoor jungle. project-1/assets/images/plantbook
