### ISSUE TITLE
Create a user story

### ISSUE THREAD

**Issue by rhazama** [katcontrerasdev/thePlantsProject#4]

**Comment by rhazama** [comment]
User with is interested in learning or owning a houseplant with little knowledge
Houseplant lover who wants to give back or help the growing houseplant community

**Comment by katcontrerasdev** [comment]
I think this one is great! 

"Houseplant lover who wants to give back or help the growing houseplant community"

**Comment by rhazama** [comment]
Houseplant coach wants to provide advice for houseplant lovers.
Database of houseplant care for the public/ community.

AS A shopper visiting an online store, I WANT to place items in a shopping cart, SO THAT I can purchase them.
As a houseplant lover visiting this website, I want to provide advice for houseplant lovers and contribute to the database of houseplant care for the public so that I can help teach the expanding houseplant community.
