### ISSUE TITLE
Wireframe/ sketch of the design

### ISSUE THREAD

**Issue by rhazama** [katcontrerasdev/thePlantsProject#8]

**Comment by rhazama** [comment]
https://drive.google.com/file/d/1d8kJArKZb_72xcFY5oepAtxFkmymHX-S/view?usp=sharing

Link to wireframe (in progress)

**Comment by katcontrerasdev** [comment]
https://fonts.google.com/specimen/Roboto 
Roboto: regular, semi-bold
